# Generated by Django 3.0 on 2021-04-13 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Numerador',
            fields=[
                ('comprobante', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('ultimo_valor', models.IntegerField(blank=True, null=True)),
                ('activo', models.CharField(choices=[('S', 'Activo'), ('N', 'Inactivo')], default='S', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'numeradores',
            },
        ),
        migrations.CreateModel(
            name='HistoricalNumerador',
            fields=[
                ('comprobante', models.CharField(db_index=True, max_length=20)),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('ultimo_valor', models.IntegerField(blank=True, null=True)),
                ('activo', models.CharField(choices=[('S', 'Activo'), ('N', 'Inactivo')], default='S', max_length=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical numerador',
                'db_table': 'historico_numerador',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
