# Generated by Django 3.0 on 2021-04-13 16:57

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import perfiles.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tabla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sessions.Session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=40, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=perfiles.models.get_image_filename)),
                ('fecha_clave', models.DateField(blank=True, null=True, verbose_name='Última actualización de clave')),
                ('email_contacto', models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail de contacto')),
                ('nivel', models.ManyToManyField(blank=True, related_name='nivel', to='tabla.Tabla')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPreferencia',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('vista', models.CharField(max_length=60)),
                ('opcion', models.CharField(max_length=60)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('caracter', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('logico', models.BooleanField(default=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical preferencia',
                'db_table': 'historico_preferencia',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPerfil',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=40, null=True)),
                ('foto', models.TextField(blank=True, max_length=100, null=True)),
                ('fecha_clave', models.DateField(blank=True, null=True, verbose_name='Última actualización de clave')),
                ('email_contacto', models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail de contacto')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'historical perfil',
                'db_table': 'historico_perfil',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vista', models.CharField(max_length=60)),
                ('opcion', models.CharField(max_length=60)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('caracter', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('logico', models.BooleanField(default=False, null=True)),
                ('usuario', models.ForeignKey(blank=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'vista', 'opcion')},
            },
        ),
    ]
