# Generated by Django 3.0 on 2021-04-13 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(choices=[('CIRCUITO', 'Circuito'), ('COMPROBANTE', 'Comprobante'), ('DEPENDENCIA', 'Dependencia'), ('ESTADO', 'Estado de expediente'), ('ESTADO_CIVIL', 'Estado Civil'), ('ESTADO_TURNO', 'Estado del ticket de turno'), ('GENERO', 'Género'), ('LOCALIDAD', 'Localidad'), ('NIVEL', 'Nivel'), ('ORIGEN', 'Origen'), ('PAIS', 'País'), ('PROVINCIA', 'Provincia'), ('ROL', 'Rol de persona '), ('ROL_INSTITUCION', 'Rol de institución'), ('SECTOR', 'Sector'), ('SUBSECTOR', 'Sub-sector'), ('SUBTEMA', 'Sub-tema'), ('TEMA', 'Tema'), ('TIPO_DEPENDENCIA', 'Tipo de dependencia'), ('TIPO_DOCUMENTO', 'Tipo de documento'), ('TIPO_NACIONALIDAD', 'Tipo de nacionalidad')], max_length=20)),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('superior_id', models.IntegerField(blank=True, null=True)),
                ('superior_entidad', models.CharField(blank=True, choices=[('CIRCUITO', 'Circuito'), ('COMPROBANTE', 'Comprobante'), ('DEPENDENCIA', 'Dependencia'), ('ESTADO', 'Estado de expediente'), ('ESTADO_CIVIL', 'Estado Civil'), ('ESTADO_TURNO', 'Estado del ticket de turno'), ('GENERO', 'Género'), ('LOCALIDAD', 'Localidad'), ('NIVEL', 'Nivel'), ('ORIGEN', 'Origen'), ('PAIS', 'País'), ('PROVINCIA', 'Provincia'), ('ROL', 'Rol de persona '), ('ROL_INSTITUCION', 'Rol de institución'), ('SECTOR', 'Sector'), ('SUBSECTOR', 'Sub-sector'), ('SUBTEMA', 'Sub-tema'), ('TEMA', 'Tema'), ('TIPO_DEPENDENCIA', 'Tipo de dependencia'), ('TIPO_DOCUMENTO', 'Tipo de documento'), ('TIPO_NACIONALIDAD', 'Tipo de nacionalidad')], max_length=20)),
                ('superior_codigo', models.CharField(blank=True, max_length=10)),
                ('valor_preferencial', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='N', max_length=1)),
                ('activo', models.CharField(choices=[('S', 'Activo'), ('N', 'Inactivo')], default='S', max_length=1)),
            ],
            options={
                'ordering': ['entidad', 'codigo'],
                'permissions': (('tabla_puede_agregar', 'Agregar'), ('tabla_puede_editar', 'Editar'), ('tabla_puede_eliminar', 'Eliminar'), ('tabla_puede_listar', 'Listar')),
            },
        ),
        migrations.CreateModel(
            name='Traduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('EXPEDIENTE', 'Expedientes'), ('VARIABLE', 'Variables'), ('PLANTILLA', 'Plantillas'), ('TABLA', 'Tablas'), ('INSUMIDO', 'Insumidos'), ('TIPO_INSUMIDO', 'Tipos de insumidos'), ('COMPROBANTES', 'Comprobantes'), ('NUMERADORES', 'Numeradores'), ('GENERAL', 'General')], default='GENERAL', max_length=60, verbose_name='Pantalla')),
                ('palabra', models.CharField(max_length=60)),
                ('traduccion', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Traducción',
                'verbose_name_plural': 'Traducciones',
                'permissions': (('traduccion_puede_agregar', 'Agregar'), ('traduccion_puede_editar', 'Editar'), ('traduccion_puede_eliminar', 'Eliminar'), ('traduccion_puede_listar', 'Listar')),
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('variable', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('F', 'Fecha'), ('C', 'Caracter'), ('N', 'Numérico'), ('L', 'Lógico')], max_length=20)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('caracter', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('logico', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('variable_puede_agregar', 'Agregar'), ('variable_puede_editar', 'Editar'), ('variable_puede_eliminar', 'Eliminar'), ('variable_puede_listar', 'Listar')),
            },
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('plantilla', tinymce.models.HTMLField(blank=True)),
                ('activo', models.CharField(choices=[('S', 'Activo'), ('N', 'Inactivo')], default='S', max_length=1)),
                ('hoja', models.CharField(default='A4', max_length=10, verbose_name='Tamaño de hoja')),
                ('tipo_comprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tabla.Tabla')),
            ],
            options={
                'permissions': (('plantilla_puede_agregar', 'Agregar'), ('plantilla_puede_editar', 'Editar'), ('plantilla_puede_eliminar', 'Eliminar'), ('plantilla_puede_listar', 'Listar')),
            },
        ),
        migrations.CreateModel(
            name='HistoricalVariable',
            fields=[
                ('variable', models.CharField(db_index=True, max_length=20)),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('F', 'Fecha'), ('C', 'Caracter'), ('N', 'Numérico'), ('L', 'Lógico')], max_length=20)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('caracter', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('logico', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical variable',
                'db_table': 'historico_variable',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTraduccion',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('EXPEDIENTE', 'Expedientes'), ('VARIABLE', 'Variables'), ('PLANTILLA', 'Plantillas'), ('TABLA', 'Tablas'), ('INSUMIDO', 'Insumidos'), ('TIPO_INSUMIDO', 'Tipos de insumidos'), ('COMPROBANTES', 'Comprobantes'), ('NUMERADORES', 'Numeradores'), ('GENERAL', 'General')], default='GENERAL', max_length=60, verbose_name='Pantalla')),
                ('palabra', models.CharField(max_length=60)),
                ('traduccion', models.CharField(max_length=60)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Traducción',
                'db_table': 'historico_traduccion',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTabla',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('entidad', models.CharField(choices=[('CIRCUITO', 'Circuito'), ('COMPROBANTE', 'Comprobante'), ('DEPENDENCIA', 'Dependencia'), ('ESTADO', 'Estado de expediente'), ('ESTADO_CIVIL', 'Estado Civil'), ('ESTADO_TURNO', 'Estado del ticket de turno'), ('GENERO', 'Género'), ('LOCALIDAD', 'Localidad'), ('NIVEL', 'Nivel'), ('ORIGEN', 'Origen'), ('PAIS', 'País'), ('PROVINCIA', 'Provincia'), ('ROL', 'Rol de persona '), ('ROL_INSTITUCION', 'Rol de institución'), ('SECTOR', 'Sector'), ('SUBSECTOR', 'Sub-sector'), ('SUBTEMA', 'Sub-tema'), ('TEMA', 'Tema'), ('TIPO_DEPENDENCIA', 'Tipo de dependencia'), ('TIPO_DOCUMENTO', 'Tipo de documento'), ('TIPO_NACIONALIDAD', 'Tipo de nacionalidad')], max_length=20)),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('superior_id', models.IntegerField(blank=True, null=True)),
                ('superior_entidad', models.CharField(blank=True, choices=[('CIRCUITO', 'Circuito'), ('COMPROBANTE', 'Comprobante'), ('DEPENDENCIA', 'Dependencia'), ('ESTADO', 'Estado de expediente'), ('ESTADO_CIVIL', 'Estado Civil'), ('ESTADO_TURNO', 'Estado del ticket de turno'), ('GENERO', 'Género'), ('LOCALIDAD', 'Localidad'), ('NIVEL', 'Nivel'), ('ORIGEN', 'Origen'), ('PAIS', 'País'), ('PROVINCIA', 'Provincia'), ('ROL', 'Rol de persona '), ('ROL_INSTITUCION', 'Rol de institución'), ('SECTOR', 'Sector'), ('SUBSECTOR', 'Sub-sector'), ('SUBTEMA', 'Sub-tema'), ('TEMA', 'Tema'), ('TIPO_DEPENDENCIA', 'Tipo de dependencia'), ('TIPO_DOCUMENTO', 'Tipo de documento'), ('TIPO_NACIONALIDAD', 'Tipo de nacionalidad')], max_length=20)),
                ('superior_codigo', models.CharField(blank=True, max_length=10)),
                ('valor_preferencial', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='N', max_length=1)),
                ('activo', models.CharField(choices=[('S', 'Activo'), ('N', 'Inactivo')], default='S', max_length=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tabla',
                'db_table': 'historico_tabla',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPlantilla',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('plantilla', tinymce.models.HTMLField(blank=True)),
                ('activo', models.CharField(choices=[('S', 'Activo'), ('N', 'Inactivo')], default='S', max_length=1)),
                ('hoja', models.CharField(default='A4', max_length=10, verbose_name='Tamaño de hoja')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_comprobante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tabla.Tabla')),
            ],
            options={
                'verbose_name': 'historical plantilla',
                'db_table': 'historico_plantilla',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
