# Generated by Django 3.0 on 2021-04-13 16:57

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(null=True, verbose_name='Mensaje')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('destinatarios', models.ManyToManyField(blank=True, help_text='Para eliminar de la selección Ctrl+Clic sobre el item', related_name='destinatarios', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(blank=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('mensaje_puede_agregar', 'Agregar'), ('mensaje_puede_editar', 'Editar'), ('mensaje_puede_eliminar', 'Eliminar'), ('mensaje_puede_listar', 'Listar')),
            },
        ),
        migrations.CreateModel(
            name='HistoricalMensaje',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('mensaje', models.TextField(null=True, verbose_name='Mensaje')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(blank=True, db_constraint=False, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical mensaje',
                'db_table': 'historico_mensaje',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visto', models.DateField(blank=True, null=True)),
                ('hora_visto', models.TimeField(blank=True, null=True)),
                ('mensaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mensajes.Mensaje')),
                ('usuario', models.ForeignKey(blank=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinatario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('destinatario_puede_agregar', 'Agregar'), ('destinatario_puede_eliminar', 'Eliminar')),
            },
        ),
    ]
