from django.urls import path
from .views import (tablas_cargar_csv,
                    cargar_localidades,
                    cargar_registros_de_entidad,
                    cargar_subordinados,
                    tablas_listar,
                    tabla_agregar,
                    tabla_editar,
                    tabla_eliminar,
                    variable_agregar,
                    variable_editar,
                    variable_eliminar,
                    variables_listar,
                    plantilla_agregar,
                    plantilla_editar,
                    plantilla_eliminar,
                    plantillas_listar,
                    seleccionar_plantilla,
                    plantilla_contenido,
                    seleccionar_tabla,
                    tabla_descripcion,
                    probar_algo,
                    etiquetas_de_grupo)

urlpatterns = [
    path('tablas_cargar_csv/', tablas_cargar_csv, name='tablas_cargar_csv'),
    path('cargar_localidades/', cargar_localidades, name='cargar_localidades'),
    path('cargar_registros_de_entidad/', cargar_registros_de_entidad, name='cargar_registros_de_entidad'),
    path('cargar_subordinados/', cargar_subordinados, name='cargar_subordinados'),
    path('tablas_listar/', tablas_listar, name='tablas_listar'),
    path('tabla_agregar/<slug:entidad>/', tabla_agregar, name='tabla_agregar'),
    path('tabla_editar/<int:id>/', tabla_editar, name='tabla_editar'),
    path('tabla_eliminar/<int:id>/', tabla_eliminar, name='tabla_eliminar'),
    path('variables_listar/', variables_listar, name='variables_listar'),
    path('variable_agregar/', variable_agregar, name='variable_agregar'),
    path('variable_editar/<slug:variable_id>/', variable_editar, name='variable_editar'),
    path('variable_eliminar/<slug:variable_id>/', variable_eliminar, name='variable_eliminar'),
    path('plantillas_listar/', plantillas_listar, name='plantillas_listar'),
    path('plantilla_agregar/', plantilla_agregar, name='plantilla_agregar'),
    path('plantilla_editar/<int:id>/', plantilla_editar, name='plantilla_editar'),
    path('plantilla_eliminar/<int:id>/', plantilla_eliminar, name='plantilla_eliminar'),
    path('seleccionar_plantilla/', seleccionar_plantilla, name='seleccionar_plantilla'),
    path('plantilla_contenido/', plantilla_contenido, name='plantilla_contenido'),
    path('seleccionar_tabla/', seleccionar_tabla, name='seleccionar_tabla'),
    path('tabla_descripcion/', tabla_descripcion, name='tabla_descripcion'),
    path('probar_algo/', probar_algo, name='probar_algo'),
    path('etiquetas_de_grupo/', etiquetas_de_grupo, name='etiquetas_de_grupo'),
]
